### ISSUE TITLE
Incompatibility with Bandits User Interface - property "requiresReload" of sliders

### ISSUE THREAD

**Issue by DeadSoon** [sirinsidiator/ESO-LibAddonMenu#103]
Im faced with a bug when using the "requiresReload" property in sliders when using LibAddonMenu together with Bandits User Interface (BUI)!

The warning symbol + tooltip appears but when I change the value, the reload/apply button (corner bottom right) dos not appear and there is also no warning dialog for reloading / discard when leaving the settings menu.

It works like expected when BUI is disabled. Because I think it is a library related issue, I posted here.

**Reproduction:**
The bug occurs in my Addon BeamMeUp. Therefore following addons are active when I reproduce the issue:

BeamMeUp - Teleporter v1.5.4 Beta -> https://www.dropbox.com/s/0w8857ugl0jxq5f/BeamMeUp-Teleporter_1.5.4_Beta.zip?dl=0
LibAddonMenu-2.0
LibDialog
LibMapPing
LibCustomMenu
LibSlashCommander
LibZone
**Bandits User Interface**

The issue occurs in the last option in the settings menu of BeamMeUp ("UI Scaling").
I used the following option configuration:
```
		 {
              type = "slider",
              name = "UI Scale",
	      tooltip = "",
	      min = 0.5,
	      max = 1.5,
	      step = 0.05,
	      decimals = 2,
	      requiresReload = true,
              getFunc = function() return mTeleSavedVars.Scale end,
              setFunc = function(value) mTeleSavedVars.Scale = value end,
			  default = teleporterDefs["Scale"],
         },
```
(The code can be found in "TeleAppUI.lua" from line 325)

**Comment by sirinsidiator** [comment]
I see that Bandits User Interface is embedding LAM in a very strange way. Will have to take a closer look at what it does.

**Comment by DeadSoon** [comment]
I want to add another bug, caused by Bandits User Interface!

For some reasons option entries, which have the property "half" are displayed incorrectly:
![image](https://user-images.githubusercontent.com/51291756/58765710-1a933180-8576-11e9-8564-6aa1a10630b8.png)

And again: Without BUI everything is fine.
I'm very surprised. BUI is very popular and it seems it causes several of display bugs in LAM.

**Comment by Binaryvector** [comment]
Is this issue and #104 fixed, now that BUI removed LAM?

**Comment by DeadSoon** [comment]
Tested with the latest version of BUI and I can confirm that both issues are fixed now.
