### ISSUE TITLE
Add build in validation functions: TextType

### ISSUE THREAD

**Issue by Baertram** [sirinsidiator/ESO-LibAddonMenu#106]
The ESO editbox control got a TextType parameter which can be used to validate the entered value.
Currently LAM got no data parameter "TextType" which can be used to set the edit box's texttype:

h5. TextType
* TEXT_TYPE_ALL
* TEXT_TYPE_ALPHABETIC
* TEXT_TYPE_ALPHABETIC_NO_FULLWIDTH_LATIN
* TEXT_TYPE_NUMERIC
* TEXT_TYPE_NUMERIC_UNSIGNED_INT
* TEXT_TYPE_PASSWORD

Please add this parameter. Thank you.

**Comment by sirinsidiator** [comment]
This got added in #110
