### ISSUE TITLE
List  LibStub as external dependency

### ISSUE THREAD

**Issue by dxmann73** [sirinsidiator/ESO-LibAddonMenu#120]
Since the r31 update AUI would barf with a lot of nil pointers. Looking through the changelist I realized that LibStub had been bundled before and isn't anymore. You might want to list this in the dependencies, I checked and only saw LibAddonMenu

Once I've installed LibStub separately all worked fine again.

Thanks
Dave

**Comment by sirinsidiator** [comment]
LibStub is no longer a dependency of LibAddonMenu. Authors have been informed and regularly reminded to update their addons to no longer use LibStub. Two years should have been more than enough time to get ready. It's up to them now to fix this.
