### ISSUE TITLE
attempt to index a nil value

### ISSUE THREAD

**Issue by dermatzeimnetz** [sirinsidiator/ESO-LibAddonMenu#121]
See Screenshot

![grafik](https://user-images.githubusercontent.com/24622818/85457124-f6026100-b59f-11ea-916a-b01d23e3dcdf.png)

I know that this might be caused from another Pluding "LuiExtended", still, is it possible to "try catch" the exception?

**Comment by sirinsidiator** [comment]
From the error message it looks like you are using an outdated version of LibAddonMenu bundled inside the MiniMap addon. Try to install the latest version from ESOUI separately.

**Comment by dermatzeimnetz** [comment]
TY very much for your effort and your very fast answer. Regarding your hint, i use Minion to install them my Addons, and it is the very last version here:
![grafik](https://user-images.githubusercontent.com/24622818/85458603-973de700-b5a1-11ea-9fc6-36ddc657f1e1.png)

**Comment by Baertram** [comment]
And delete the bundled LAM version from the MiniMap folder at best so it won't be loaded anymore!
Maybe it was called from the addon's txt file by hardcoded lines like
/libs/LibAddonMenu-2.0/LibAddonMenu-2.0/controls/editbox.lua
...
/libs/LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua

Remove these lines and replace them via this entry:
## DependsOn: LibAddonMenu-2.0>=31

And tell the addon author of the minimap (or the bundled addon LUI e.g.) to update the libraries, include them with their txt files OR remove them from the addon's subfolders!

He can read all the information about it here:
https://www.esoui.com/forums/showthread.php?t=8765&highlight=LibStub

**Comment by sirinsidiator** [comment]
I've just checked and the MiniMap addon still embeds LAMr26 the old way, which is likely why you get that issue even when you install it separately. Simply deleting the MiniMap/LibAddonMenu-2.0 folder should do the trick.
