### ISSUE TITLE
dropdown widget choicesValues does not accept boolean "false"

### ISSUE THREAD

**Issue by Baertram** [sirinsidiator/ESO-LibAddonMenu#128]
If you pass in a false boolean to the choicesValues the current dropdown widget code will just use the name of the dropdown entry, as all checks for value are done via 
```valueToUse = entry.value or entry.name``` and the boolean false will always lead to entry.name in that case.

See pull request #127  for the fix

**Comment by sirinsidiator** [comment]
thanks. merged the fix just now.
