### ISSUE TITLE
Submenu with dropdown as last element doesn't display dropdown menu

### ISSUE THREAD

**Issue by dethmourne** [sirinsidiator/ESO-LibAddonMenu#133]
> When I have a submenu that has as the last element a dropdown and I select the dropdown to look at the list - that list is clipped at the bottom and right side when it runs into the edge of the submenu. Other dropdowns above it (using the exact same choice lists) work as expected.
> 
> If I could move up the dropdown so that it is not last, it would work - but all of my elements are dropdowns so I'd just be choosing which one will break.
> 
> The same code worked as expected last night (prior to the update).

From the ESOUI comments page. Confirmed independently on multiple addons that this is happening.

**Comment by jimmon89** [comment]
![Screenshot_20231031_105226](https://github.com/sirinsidiator/ESO-LibAddonMenu/assets/6391541/9bd1c252-96bf-4a17-ad85-f909cfbffcd3)
having the same issue
you can see an example of what is going on in the addon settings easily in my screenshot
under blacksmithing, the dropdown for temper is almost entirely cut off

**Comment by sirinsidiator** [comment]
Thanks for the report. ZOS is aware and looking into a fix, since it happened due to a change they made in the latest update.
I'll check if there is some easy workaround that can be made in LAM, but otherwise I'll just wait for the game to correct the issue.

**Comment by jimmon89** [comment]
fair enough
hopefully you can find a workaround
but at least now we know it's being looked at by ZOS

**Comment by dethmourne** [comment]
> Thanks for the report. ZOS is aware and looking into a fix, since it happened due to a change they made in the latest update. I'll check if there is some easy workaround that can be made in LAM, but otherwise I'll just wait for the game to correct the issue.

Need a "Dammit ZOS" label for issues lol

**Comment by jimmon89** [comment]
absolute legend
will post if i notice any issues that most likely are caused by libAddonMenu
cheers!
