### ISSUE TITLE
Guilds listed in dropdown menu are missing.

### ISSUE THREAD

**Issue by Zynn3d** [sirinsidiator/ESO-LibAddonMenu#138]
Since the update last night, 03/11/2024, I can't select different guilds to view roster because the dropdown menu is empty, nothing is listed.
When you hit G to view guild roster, you cannot select another guild.
Also, when you are at the bank and want to select a different guild bank, the guild names are also missing on that dropdown menu.
Guild name reappear when disabling LibAddonMenu.
Already searched for and deleted other LibAddonMenu folders from other mods that may have included them.

![ESO Select Guild Bank](https://github.com/sirinsidiator/ESO-LibAddonMenu/assets/12665695/f7bcc0ba-bfdb-4b94-acd5-850d6f538dee)
![ESO Select Guild](https://github.com/sirinsidiator/ESO-LibAddonMenu/assets/12665695/4b502089-74e2-4cd8-95e8-7aec46fa60b0)

**Comment by sirinsidiator** [comment]
This is unlikely to be caused by LAM. You are using other addons which depend on LAM, so when you disable it, they will be disabled too. Try start turning off addons instead of libraries to find the culprit.

**Comment by Zynn3d** [comment]
Turns out LibScrollableMenu was the culprit.  Apologies.
    On Monday, March 11, 2024 at 05:03:12 PM PDT, sirinsidiator ***@***.***> wrote:  
 
 


Closed #138 as completed.
