### ISSUE TITLE
parenting -TopLevelControl ZO_ComboBoxDropdown_Singleton_Keyboard 

### ISSUE THREAD

**Issue by user99** [sirinsidiator/ESO-LibAddonMenu#139]
I only had this occur in the logs on one login, but it was listed about 12 times when it did and the UI was broken. I am using minion and this only occured the once and after update to 41.  I thought it worth reporting. 

TopLevelControl ZO_ComboBoxDropdown_Singleton_Keyboard cannot be parented to LAMAddonSettingsWindow, it must be parented to GuiRoot

|rstack traceback:
[C]: in function 'SetParent'
user:/AddOns/LibAddonMenu-2.0/controls/dropdown.lua:396: in function 'LAMCreateControl.dropdown'
	<Locals> parent = ud, dropdownData = [table:1]{name = "Label Font Name", width = "full", default = "BOLD_FONT", type = "dropdown"}, control = ud, countControl = [table:2]{scrollCount = 65, comboboxCount = 1}, name = "LAM", comboboxCount = 1, combobox = ud, dropdown = [table:3]{horizontalAlignment = 0, m_name = "LAMCombobox1", m_font = "ZoFontGame", m_height = 250, m_sortsItems = F, m_isDropdownVisible = F, m_enableMultiSelect = F, m_spacing = 0, m_sortOrder = T, m_containerWidth = 135} </Locals>
user:/AddOns/DailyAlchemy/Setting.lua:56: in function '(anonymous)'
	<Locals> parent = ud, dropdownData = [table:1] </Locals>
user:/AddOns/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:861: in function '(anonymous)'
[C]: in function 'pcall'
user:/AddOns/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:861: in function 'CreateAndAnchorWidget'
	<Locals> parent = ud, widgetData = [table:1], offsetX = 0, offsetY = 0, anchorTarget = ud, wasHalf = F </Locals>
user:/AddOns/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:917: in function 'CreateWidgetsInPanel'
	<Locals> parent = ud, widgetDataTable = [table:4]{}, startIndex = 1, endIndex = 20, i = 9, widgetData = [table:1], widgetType = "dropdown", offsetX = 0, isSubmenu = F </Locals>
user:/AddOns/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:897: in function 'nextCall'
user:/AddOns/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:935: in function 'DoCreateSettings'
	<Locals> nextCall = user:/AddOns/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:896 </Locals>
user:/AddOns/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:937: in function 'DoCreateSettings'
	<Locals> nextCall = user:/AddOns/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:888 </Locals>
/EsoUI/Libraries/Globals/globalapi.lua:263: in function '(anonymous)'

**Comment by sirinsidiator** [comment]
It looks like you are using an outdated version of LAM. Please make sure to delete all copies of the LibAddonMenu folder inside your AddOns folder and install it freshly to make sure Minion doesn't get it wrong.
