### ISSUE TITLE
settings menu creation performance

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibAddonMenu#17]
Settings menus of addons with many options (e.g. Destinations, pChat) produce a noticeable hang.
Seems like it is time to review the CreateOptionsControls function.

First step will be collecting data on what takes how much time inside that method.
Then we'll have to see what we can do in order to fix it.
Might be necessary to split it into multiple calls and only create n controls at a time.

**Comment by merlight** [comment]
I have recursive CreateOptionsControls stashed somewhere, it's DRY and simple, you could start with that. Then perhaps defer `submenu` contents creation until it's opened.

I don't think you can't pick some arbitrary `n` controls to create. The user must provide some hit. Like by splitting them into submenus, which can be populated individually later.

There's another possibility -- one which could drastically limit flexitiblity -- replace `ZO_ScrollContainer` inside `panel` with `ZO_ScrollList`. Basically you can `AddDataType` for each row (*each* being a brute force solution to various (and dynamic!) control heights), and their contents (i.e. actual LAM widgets) will be created when they scroll into view. To make this work, you would need to know the height of any widget given only its `widgetData`.

Now, if we care about strong backwards compatibilty, we can add a `listpanel` widget. That way the decision would be up to the user, and it'd also be their responsibility to only use options with *computable* height (or include the desired height in widgetData).

**Comment by sirinsidiator** [comment]
Creating submenu controls only on open is also something I thought about, but it won't help with everything. pChat just has a lot of options in the main panel.

What I meant with create n controls is that instead of running a loop with 100 control creations, we throttle it and only create 10 at a time. We still create all of them, but leave some time for the game so it does not hang.

Using a scroll list could help. Maybe it is possible to set the row height after the control was created?
I will try it, but if there is no way to do it without loosing backwards compatibility, I am against it.

**Comment by merlight** [comment]
> Using a scroll list could help. Maybe it is possible to set the row height after the control was created?

It's a chicken&egg problem. In order to properly setup a scrollbar, you need to know the total height of the contents. If you don't know the height of a control before you create it, you can't defer the creation until it scrolls into view.

**Comment by sirinsidiator** [comment]
Didn't think about the scrollbar... Maybe we could use an estimate and correct it with each newly created control? Might look a bit weird though.

**Comment by sirinsidiator** [comment]
Tried to create controls asynchronously, but some addons rely on them being created instantly and throw errors now... Guess we'll have to slim down the widgets themselves.

**Comment by sirinsidiator** [comment]
Created #19 which will fix this.

**Comment by merlight** [comment]
The stash I had didn't apply cleanly. It was from way before optionsTable "validation" (and I still think ipairs is superior). So I just extracted the recursive CreateOptionControls function and created a gist: 
https://gist.github.com/merlight/0fe43ed94a4d46477f5e
