### ISSUE TITLE
library loading order

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibAddonMenu#2]
@votan73 wrote:
>I'm still doubtful about loading libAddonMenu, and I think I have something:
>Look at the code and imagine this:
>We are in the pure embedded scenario and there are three addons.
>One is using r11, one was up-to-date until now using r16 and one uses r17.
>
>As long as the load order is 17,11,16 or 17,16,11 everything is good. Check.
>But in worst case the load order is 11,16,17.
>
>    Every version of the library gets the one and only reference to lam. Check.
>    If the library passes the version check, newer functions are registered to lam. Check.
>    But what is with CreateAddonSettingsPanel and CreateAddonList? They are called everytime the library passes the version check, too. In this case: three times.
>    Inside CreateAddonSettingsPanel there is a global LAMSettingsPanelCreated. Good. But this variable is set to true by the first library, in this case not the newest one.
>    And look, there is one API version relevant call inside CreateAddonSettingsPanel.
>
>I think, we have to defer the calls of CreateAddonSettingsPanel and CreateAddonList with EVENT_ADD_ON_LOADED by always re-registering a newer handler.
>We should change LAMSettingsPanelCreated from true to MINOR and write a warning, if LAMSettingsPanelCreated is not MINOR.
>Or deferring the calls even more to options scene showing.
>
>Or do I miss something?

**Comment by sirinsidiator** [comment]
Could this be what happened in http://www.esoui.com/forums/showthread.php?t=4238?

**Comment by votan73** [comment]
Yes, that is what happened there.
I think there is no chance to prevent this with newer code. We just could write a better alert message, so the user knows what to do.

**Comment by votan73** [comment]
I could provide a scenario code. Basically three addons those load order is made "worst case" by dependency.

**Comment by votan73** [comment]
The good news is: Where is no error, if the "old" addons using r16.

**Comment by sirinsidiator** [comment]
Shouldn't it help if we change things so that the library does not do any work until all addons are fully loaded? For example use lazy initialization and run only the first time we open the menu, or maybe even on PLAYER_ACTIVATED.

I only found two calls at the end of the main lua file which we have to wrap in order to achieve this:
```lua
CreateAddonSettingsPanel()
CreateAddonList()
```

It won't help with older versions, but should prevent the issue in the future.

**Comment by votan73** [comment]
Already prepared: If delaying this to PLAYER_ACTIVATED, the panels are not there!?!
Test this and change the event to see what happens:

--INTERNAL FUNCTION
--Will be call for the last library, which passed the version check => the newest
local function Initialize(event, name)
	if name:find("^ZO_") then return end

	EVENT_MANAGER:UnregisterForEvent(MAJOR, EVENT_ADD_ON_LOADED)

	--INITIALIZING
	CreateAddonSettingsPanel()
	CreateAddonList()
end

EVENT_MANAGER:UnregisterForEvent(MAJOR, EVENT_ADD_ON_LOADED)
EVENT_MANAGER:RegisterForEvent(MAJOR, EVENT_ADD_ON_LOADED, Initialize)

**Comment by merlight** [comment]
Hm, I should've checked these issues earlier. I might have solved a bit of this. I call the functions that create LAM window and add it to the game menu when someone calls RegisterAddonPanel. There are addons that do that before the LOADED event, but these should be fixed -- actually it's in their interest to initialize LAM as the last thing in their onLoaded, so that if LAM breaks, they have a chance to work.

**Comment by merlight** [comment]
I've just been hit by this. I installed a bunch of addons to check that I didn't break something in LAM, and got two Addon Settings entries. Luckily the one with the old look has no addons in it ;)

**Comment by merlight** [comment]
We could point out the evil addon in the message. Old-version Initialize happens when an addon with that version calls RegisterAddonPanel before ON_LOADED event, right?

```lua
local safeToInitialize = false

local myNAME = table.concat("r", MAJOR, MINOR)
local function onLoaded(_, addonName)
    -- no need to check addonName, the first hit will do
    EVENT_MANAGER:UnregisterForEvent(myNAME, EVENT_ADD_ON_LOADED)
    safeToInitialize = true
end
EVENT_MANAGER:RegisterForEvent(myNAME, EVENT_ADD_ON_LOADED, onLoaded)

function lam:RegisterAddonPanel(addonID, panelData)
    if(not LAMSettingsPanelCreated) then
        if not safeToInitialize then
            local msg = string.format("LAM panel '%s' registered too early. This might break Addon Settings menu.", addonID)
            zo_callLater(function() d(msg) end, 3000)
...
```

**Comment by sirinsidiator** [comment]
Good that you point that out. This is something I haven't thought about yet, but can cause my fix to fail from protecting us.
Again it won't help with the older versions before r17, but for the future it will help prevent any issues that may arise.

**Comment by sirinsidiator** [comment]
Added and tested. It now prints a warning when a panel is registered before addon load has completed if no older version of LAM has been loaded before and it will point out that an old version of LAM has been detected otherwise.

**Comment by merlight** [comment]
So after downloading the latest PTS I got error spam as usual because every addon I installed was enabled again. But at least it forced me to try to track down their load order. Here's what I got:

![library load order](http://s28.postimg.org/qsf7ipxxp/loadevents.png)

The two addons at the top call RegisterAddonPanel before any LOADED events. What surprised me was that these events come in apparently random order -- LAM is announced after many addons that depend on it.

**Comment by sirinsidiator** [comment]
Nice job! Guess these two will have to change once r17 is available. Maybe we should contact the authors?
The random load order does not really surprise me, considering that saved vars manage to serialize data in random order.

**Comment by merlight** [comment]
Those two are on ancient versions on LAM1, they got caught because I have LAM1to2 adaptor posing as LAM1 ;) GSSE might've been updated to LAM2, I don't know since I stopped using it like 8 months ago :)

**Comment by sirinsidiator** [comment]
Ok. Still means the LAM1to2 adapter needs an update ;)
