### ISSUE TITLE
Let text fields use standard ESO localization

### ISSUE THREAD

**Issue by s42ky** [sirinsidiator/ESO-LibAddonMenu#22]
Allow the item name, tooltip, description, and other text display take in a string ID for localization instead of a string.

Example current:
```Lua
LAMCreateControl.checkbox(parent, {
        type = "checkbox",
        name = GetString(SI_SOME_CHECKBOX_NAME),
        tooltip = GetString(SI_SOME_CHECKBOX_TOOLTIP),
        -- ....
}
```

With change:
```Lua
LAMCreateControl.checkbox(parent, {
        type = "checkbox",
        name = SI_SOME_CHECKBOX_NAME,
        tooltip = SI_SOME_CHECKBOX_TOOLTIP,
        -- ....
}
```

This would be a simple type check since IDs are integers. Not really necessary, but would be a nice integration to promote localizing.

**Comment by sirinsidiator** [comment]
Has been implemented for all name, tooltip and warning values. Dropdowns may also profit from this, but there are some other changes necessary before it will work. Going to handle this in a separate ticket.
