### ISSUE TITLE
Functions as tooltip

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibAddonMenu#24]
Ayantir wrote:
>Same request for tooltips.

>Why :
If I disable a control, user don't know why.
So we explain on tooltips.
Sometimes the reason isin LAM, sometime not. Sometimes it can be combinaisons of reasons.
If I try to cheat and changing tooltips when I change an option

>ex :
>```lua
    optionsTable[index] = {
        type = "checkbox",
        name = pChat.lang.useESOcolors,
        tooltip = pChat.lang.useESOcolorsTT,
        getFunc = function() return pChat.opts.useESOcolors end,
        setFunc = function(newValue)
            pChat.opts.useESOcolors = newValue
            pChat.initLAMTooltips()
        end,
        width = "full",
        default = defaults.useESOcolors,
    }
    function pChat.initLAMTooltips()
        if pChat.opts.useESOcolors then
            pChat.lam.sayTT = pChat.lang.useESOcolorsErrorTT
            ....
        end
    end
    optionsTable[index] = {
        type = "colorpicker",
        name = pChat.lang.say,
        tooltip = pChat.lam.sayTT,
        getFunc = function() return pChat.getColour(pChat.opts.colours[2*CHAT_CHANNEL_SAY]) end,
        setFunc = function(r, g, b) pChat.opts.colours[2*CHAT_CHANNEL_SAY] = pChat.makeColour(r, g, b) end,
        default = pChat.defaultColour(defaults.colours[2*CHAT_CHANNEL_SAY]),
        disabled = function() return pChat.opts.useESOcolors end,
    }
```

>It won't work neither. Control defined with pChat.lang.say will still get its old tooltip because LAM optionTable is only refreshed when you :RegisterOptionControls. I'll could rebuild my optionsTable with

>```lua
    LAM:RegisterOptionControls("pChatOptions", optionsTable)
```
>in order to work, but generally users change their multiple options before leaving it.
I've also tried to add in my setFunc : LAM:RegisterOptionControls("pChatOptions", optionsTable)
I won't work neither.

>If for a lot of addons, building table only at the startup is a good choice, when you get an addon with huge settings panels and complex code to decide if or not an option is enabled, maybe an optional setting in the controls could be interesting.

>```lua
    name= "blabla",
    getfunc = ...
    setFunc = ..
    refreshPanel = true
```

**Comment by Ayantir** [comment]
Hello here,

I'm new to GitHub, so i've just uploaded a modified r-18 for my little feature :)
Include the metafile, the 18 rev, all modifications done in controls files and updated control revision too. tested, seems working as a charm.

https://www.dropbox.com/s/n8u7f3a4u9imzdz/LibAddonMenu-2.0r18.zip?dl=0

It is basically a : 

```lua
	if checkboxData.tooltip then
		if type(checkboxData.tooltip) == "string" then
			control.data.tooltipText = checkboxData.tooltip
		elseif type(checkboxData.tooltip) == "function" then
			control.data.tooltipText = tostring(checkboxData.tooltip())
		end
	end
```

**Comment by sirinsidiator** [comment]
Hi Ayantir,

I created a pull request based on your modified version and will include it in the next release.
There was a problem with controls that did not have a data property that seems to have slipped past you when you copy pasted it to every file. ;)

I'd also like to ask you to not upload zip files with names like LibAddonMenu-2.0r18 as they can easily be mistaken for an official release. If any addon author then uses this inofficial version in one of his addons, the official r18 might then not load correctly anymore once it is out. This has happened with r17 before and I would like to avoid it to happen again in the future.
