### ISSUE TITLE
OpenToPanel does not refresh the opened panel

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibAddonMenu#28]
Baertram reported that a panel that is opened via the OpenToPanel function won't update the state of the shown settings.
For example if the panel was opened and some setting got deactivated, then it is closed and the setting does get activated again via different means, it will stay deactivated when the panel is opened with this function.

**Comment by merlight** [comment]
You could change OnShow handler to OnEffectivelyShown
```lua
panel:SetHandler("OnEffectivelyShown", ToggleAddonPanels)
```

And tell Atropos my advice to pre-hook that (#27) was really bad. OnEffectivelyShown handler gets called before OnShown, so the first OnEffectivelyShown would not have the panel's controls created yet.

**Comment by sirinsidiator** [comment]
Looks like this was also related to #33 and #35 and is fixed now.
