### ISSUE TITLE
Reload UI flag

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibAddonMenu#47]
Many addons automatically force a UI reload when a setting needs one. This is very bad for the user experience. Instead of immediately reloading, a button should show up when such a setting is changed and when the user leaves the panel, a dialog should ask if the UI should be reloaded now in order to apply the changes. Also after the reload, the previously opened settings panel should be reopened again.

**Comment by Randactyl** [comment]
The panel should only reopen if the user selected the button, right? Not if they reloaded from the reminder dialog after they closed the panel.

**Comment by sirinsidiator** [comment]
Yes. When they already tried to close the menu there is no point in reopening it.
