### ISSUE TITLE
Nested submenus won't update controls in the submenus properly

### ISSUE THREAD

**Issue by Baertram** [sirinsidiator/ESO-LibAddonMenu#53]
If you create a submenu in a submenu, and add controls to the nested submenu, the controls won't be updated properly.
e.g. the disbaled flag is not set and the color is not changed.

**Comment by sirinsidiator** [comment]
LAM2 has currently no support for nested submenus, but it should be easy to implement. I'll take a look and see if I can whip something up for r22.

**Comment by sirinsidiator** [comment]
still not working.
