### ISSUE TITLE
Open addon URL page

### ISSUE THREAD

**Issue by Ayantir** [sirinsidiator/ESO-LibAddonMenu#57]
local panelData = {
      type = "panel",
      url = "http://www.esoui.com/downloads/info7-LibAddonMenu.html#comments"
   }

-> RequestOpenUnsafeURL(panelData.url)

+ In the Gui here : 

![www-lam](https://cloud.githubusercontent.com/assets/9476643/17374990/61f37f9e-59af-11e6-9054-89a517a15ff3.png)

**Comment by sirinsidiator** [comment]
I was already thinking of adding that. :)

**Comment by sirinsidiator** [comment]
I added a clickable text next to the author text which sends you to the website. The property for the panel is also called website.
