### ISSUE TITLE
Icon Picker

### ISSUE THREAD

**Issue by Scootworks** [sirinsidiator/ESO-LibAddonMenu#62]
`Too many anchors processed. Tail of anchor list:
LAMIconPickerScrollContainerScrollBarThumbMunge->
->
->
->
LAMIconPickerScrollContainerScrollBarThumbMunge`

Tested with Phinix Poison Master -> Settings -> while clicking on icon picker symbol

**Comment by sirinsidiator** [comment]
Thanks. I'll check what's up with that.

**Comment by sirinsidiator** [comment]
Doesn't seem to happen anymore, so it was most likely caused by incorrect usage of the icon picker.
