### ISSUE TITLE
Add a polish translation code

### ISSUE THREAD

**Issue by EmiruTegryfon** [sirinsidiator/ESO-LibAddonMenu#73]
Yoo. I have translated the code into the language version of the add-on to polish.

    pl = {
        PANEL_NAME = "Dodatki",
        VERSION = "Wersja: <<X:1>>",
        WEBSITE = "Odwiedź stronę",
        PANEL_INFO_FONT = "EsotwZH/fonts/univers57.otf|14|soft-shadow-thin",
        RELOAD_UI_WARNING = "Zmiany będą widoczne po ponownym załadowaniu UI.",
        RELOAD_DIALOG_TITLE = "Wymagane przeładowanie UI",
        RELOAD_DIALOG_TEXT = "Niektóre zmiany wymagają ponownego załadowania UI. Czy chcesz teraz ponownie załadować, czy porzucić zmiany?",
        RELOAD_DIALOG_RELOAD_BUTTON = "Przeładuj",
        RELOAD_DIALOG_DISCARD_BUTTON = "Porzuć",
    },

Please reply and thanks.
Emiru Tegryfon

**Comment by sirinsidiator** [comment]
Thanks. I'll include it in the next version.

**Comment by EmiruTegryfon** [comment]
Thank you.

26.06.2017 17:43 "sirinsidiator" <notifications@github.com> napisał(a):
