### ISSUE TITLE
Small error polish translate.

### ISSUE THREAD

**Issue by EmiruTegryfon** [sirinsidiator/ESO-LibAddonMenu#74]
I found my  error
This
PANEL_INFO_FONT = "EsotwZH/fonts/univers57.otf|14|soft-shadow-thin",

That
PANEL_INFO_FONT = "EsoPL/fonts/univers57.otf|14|soft-shadow-thin",

**Comment by sirinsidiator** [comment]
Thanks. It's fixed.
