### ISSUE TITLE
Change PL translation

### ISSUE THREAD

**Issue by EmiruTegryfon** [sirinsidiator/ESO-LibAddonMenu#76]
I would remove one line in pl translation

remove
PANEL_INFO_FONT = "EsoPL/fonts/univers57.otf|14|soft-shadow-thin",

It is very important
thanks

**Comment by sirinsidiator** [comment]
Ok. I'll remove the line.
Btw you shouldn't create a new issue for every little change to the translation while the new version is not released. Just reply to the original issue #73 when you need additional changes and I will reopen it until r24 is released.

**Comment by EmiruTegryfon** [comment]
I'll remember. Thank you.

09.07.2017 15:59 "sirinsidiator" <notifications@github.com> napisał(a):

Ok. I'll remove the line.
Btw you shouldn't create a new issue for every little change to the
translation while the new version is not released. Just reply to the
original issue #73
<https://github.com/sirinsidiator/ESO-LibAddonMenu/issues/73> when you need
additional changes and I will reopen it until r24 is released.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sirinsidiator/ESO-LibAddonMenu/issues/76#issuecomment-313921518>,
or mute the thread
