### ISSUE TITLE
Panel not refreshing when opened

### ISSUE THREAD

**Issue by Dolgubon** [sirinsidiator/ESO-LibAddonMenu#82]
If the panel is registered for refresh, it does not refresh when you open the addon settings menu and it's the one currently open

Repro:
Open the addon settings menu, and navigate to the panel with registerForRefresh on.
Go out of the addon settings menu without choosing another addon's settings.
Change some setting using something else (e.g. /script)
Open up the addon settings menu. The panel will still show the old setting.
If you change some other setting, or navigate to another addon's settings and then back to the original one, the panel will show the correct settings.

The function RefreshPanel is not called.

**Comment by sirinsidiator** [comment]
This should be fixed in r27
