### ISSUE TITLE
Scrollable dropdown

### ISSUE THREAD

**Issue by Baertram** [sirinsidiator/ESO-LibAddonMenu#83]
The scrollabale dropdown box within LAM is always using the standard value of 10 items for the scrollbar, even if there is only 1 entry in the dropdown box.

The variable DEFAULT_VISIBLE_ROWS is used in line 347 if the "scrollable" parameter is a boolean e.g.:
`local visibleRows = type(dropdownData.scrollable) == "number" and dropdownData.scrollable or DEFAULT_VISIBLE_ROWS
`

But if the number of rows in the dropdowns entries is below this default value of 10 rows, the scrollbar is too long/high.

Example, scrollable parameter = true, so DEFAULT_VISIBLE_ROWS will be used (10 lines):
![image](https://user-images.githubusercontent.com/1195208/38387513-4ddbf316-3918-11e8-9c69-993f4a9fff49.png)

This should also apply to if the scrollable parameter is specified as an integer value. If this is > entries in the dropdown the scrollbar will be too high too.

**Comment by sirinsidiator** [comment]
fixed in r27
